name: Deploy PrintIt App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: SecretKeys 

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Build with Secrets
      shell: bash
      run: |
        dotnet build --configuration Release
      env:
        Stripe__SecretKey: ${{ secrets.Stripe__SecretKey }}
        Authentication__Google__ClientSecret: ${{ secrets.Authentication__Google__ClientSecret }}

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: printit-app         # <-- Your App Service name
        slot-name: production         # <-- Use your slot or "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish