name: Build and deploy ASP.Net Core app to Azure Web App - Print-it

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build solution
        run: dotnet build PrintIt/PrintIt.sln --configuration Release

      - name: Publish solution
        run: dotnet publish PrintIt/PrintIt.sln -c Release -o ${{ github.workspace }}/myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E217FCAB05F64B1895B3CF817391F6A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C6F0E5A5321C49C490E26BCACC16FC01 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15A6966EF8074A6286DC9ECD30AAF7FA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'print-it3d'
          slot-name: 'Production'
          package: ${{ github.workspace }}/dotnet-app
          app-settings: |
            Stripe__SecretKey=${{ secrets.STRIPE_SECRETKEY }}
            Stripe__PublishableKey=${{ secrets.STRIPE_PUBLISHABLEKEY }}
            Authentication__Google__ClientId=${{ secrets.GOOGLE_CLIENTID }}
            Authentication__Google__ClientSecret=${{ secrets.GOOGLE_CLIENTSECRET }}