name: Build and deploy ASP.Net Core app to Azure Web App - Print-it

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up .NET 9 SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build the project
      - name: Build project
        run: dotnet build PrintIt/PrintIt/PrintIt.csproj --configuration Release

      # Publish the project
      - name: Publish project
        run: dotnet publish PrintIt/PrintIt/PrintIt.csproj -c Release -o ${{ github.workspace }}/publish --self-contained false

      # Upload published files as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E217FCAB05F64B1895B3CF817391F6A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C6F0E5A5321C49C490E26BCACC16FC01 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15A6966EF8074A6286DC9ECD30AAF7FA }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'print-it3d'
          package: ${{ github.workspace }}/publish

      # Set App Service application settings
      - name: Set Azure App Service Application Settings
        uses: azure/webapps-config@v2
        with:
          app-name: 'print-it3d'
          configuration-strings: |
            Stripe__SecretKey=${{ secrets.STRIPE_SECRETKEY }}
            Stripe__PublishableKey=${{ secrets.STRIPE_PUBLISHABLEKEY }}
            Authentication__Google__ClientId=${{ secrets.GOOGLE_CLIENTID }}
            Authentication__Google__ClientSecret=${{ secrets.GOOGLE_CLIENTSECRET }}